/********************************************************************
* /home/fujigami/retro/lowe/source/macro/src/macroRootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/fujigami/retro/lowe/source/macro/src/macroRootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemacroRootDict();
extern void G__cpp_setup_inheritancemacroRootDict();
extern void G__cpp_setup_typetablemacroRootDict();
extern void G__cpp_setup_memvarmacroRootDict();
extern void G__cpp_setup_globalmacroRootDict();
extern void G__cpp_setup_memfuncmacroRootDict();
extern void G__cpp_setup_funcmacroRootDict();
extern void G__set_cpp_environmentmacroRootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/fujigami/retro/lowe/source/macro/include/eventdisplay.hh"
#include "/home/fujigami/retro/lowe/source/macro/include/goodness_data.hh"
#include "/home/fujigami/retro/lowe/source/macro/include/likelihood_direction_data.hh"
#include "/home/fujigami/retro/lowe/source/macro/include/AnalizedData.hh"
#include "/home/fujigami/retro/lowe/source/macro/include/CSearch_range.hh"
#include "/home/fujigami/retro/lowe/source/macro/include/C4Number.hh"
#include "/home/fujigami/retro/lowe/source/macro/include/FileList.hh"
#include "/home/fujigami/retro/lowe/source/macro/include/efficiency.hh"
#include "/home/fujigami/retro/lowe/source/macro/include/HistByTree.hh"
#include "/home/fujigami/retro/lowe/source/macro/include/HistError.hh"
#include "/home/fujigami/retro/lowe/source/macro/include/HistBias.hh"
#include "/home/fujigami/retro/lowe/source/macro/include/MultiRunAnalizeManager.hh"
#include "/home/fujigami/retro/lowe/source/macro/include/OneRunAnalizeManager.hh"
#include "/home/fujigami/retro/lowe/source/macro/include/AngleRange.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__macroRootDictLN_TClass;
extern G__linked_taginfo G__macroRootDictLN_TBuffer;
extern G__linked_taginfo G__macroRootDictLN_TMemberInspector;
extern G__linked_taginfo G__macroRootDictLN_TObject;
extern G__linked_taginfo G__macroRootDictLN_TNamed;
extern G__linked_taginfo G__macroRootDictLN_TCollection;
extern G__linked_taginfo G__macroRootDictLN_string;
extern G__linked_taginfo G__macroRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__macroRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroRootDictLN_TObjArray;
extern G__linked_taginfo G__macroRootDictLN_TClonesArray;
extern G__linked_taginfo G__macroRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__macroRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroRootDictLN_TArray;
extern G__linked_taginfo G__macroRootDictLN_TArrayD;
extern G__linked_taginfo G__macroRootDictLN_TAttLine;
extern G__linked_taginfo G__macroRootDictLN_TAttFill;
extern G__linked_taginfo G__macroRootDictLN_TAttMarker;
extern G__linked_taginfo G__macroRootDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__macroRootDictLN_TF1;
extern G__linked_taginfo G__macroRootDictLN_TH1D;
extern G__linked_taginfo G__macroRootDictLN_TH1;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__macroRootDictLN_TH2D;
extern G__linked_taginfo G__macroRootDictLN_TArc;
extern G__linked_taginfo G__macroRootDictLN_TPave;
extern G__linked_taginfo G__macroRootDictLN_Eventdisplay;
extern G__linked_taginfo G__macroRootDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TVector3;
extern G__linked_taginfo G__macroRootDictLN_TLorentzVector;
extern G__linked_taginfo G__macroRootDictLN_goodness_data;
extern G__linked_taginfo G__macroRootDictLN_l_dir_data;
extern G__linked_taginfo G__macroRootDictLN_AnalizedData;
extern G__linked_taginfo G__macroRootDictLN_C4Number;
extern G__linked_taginfo G__macroRootDictLN_CSearch_range;
extern G__linked_taginfo G__macroRootDictLN_TSeqCollection;
extern G__linked_taginfo G__macroRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__macroRootDictLN_FileList;
extern G__linked_taginfo G__macroRootDictLN_efficiency;
extern G__linked_taginfo G__macroRootDictLN_TTree;
extern G__linked_taginfo G__macroRootDictLN_TFile;
extern G__linked_taginfo G__macroRootDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__macroRootDictLN_TH1DByTree;
extern G__linked_taginfo G__macroRootDictLN_TH1DByTreecLcLAxis;
extern G__linked_taginfo G__macroRootDictLN_HistError;
extern G__linked_taginfo G__macroRootDictLN_HistBias;
extern G__linked_taginfo G__macroRootDictLN_MultiRunAnalizeManager;
extern G__linked_taginfo G__macroRootDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__macroRootDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroRootDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__macroRootDictLN_reverse_iteratorlEvectorlEfloatcOallocatorlEfloatgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroRootDictLN_WCSimRootEvent;
extern G__linked_taginfo G__macroRootDictLN_WCSimRootGeom;
extern G__linked_taginfo G__macroRootDictLN_AngleRange;
extern G__linked_taginfo G__macroRootDictLN_OneRunAnalizeManager;

/* STUB derived class for protected member access */
